### ISSUE TITLE
Provide a place for a discussion

### ISSUE THREAD

**Issue by redbaron** [reverbrain/grape#1]
Couldnt find a place to ask a question regarding grape and thus opening a ticket to ask you to provide a place where discussion can take place.

Please execuse me if it is already exist, but I found no maillist on ioremap/reverbrain websites. Simple drupal comments are not enough to build a vibrant community, right? I'd prefer Google groups, but it is really your call which solution to choose as long as it is announced and properly advertised on your product websites.

Thank you.

**Comment by bioothod** [comment]
Yes, you are right
I've just created a group to discuss all our technologies

https://groups.google.com/forum/?fromgroups=#!forum/reverbrain
