### ISSUE TITLE
cocaine-plugins doesn't build binary sandbox anymore

### ISSUE THREAD

**Issue by redbaron** [reverbrain/grape#5]
libcocaine-plugin-binary is disabled in recent cocaine-plugins, which leaves grapes with unsatisfied dependencies. How grape should be built against latest cocaine then?

**Comment by bioothod** [comment]
New grape will use native framework instead of binary plugin, stay tuned!

**Comment by bioothod** [comment]
So I close it so far

**Comment by redbaron** [comment]
after API change grape isn't compatible with latest elliptics too. I made small patch locally to fix API compatibility, but it seems that you are about to update grape anyway, so I think there is no need for pull request, am I right?

**Comment by bioothod** [comment]
I can apply your patch for sure, but new grape will be ready in a matter of days, maybe weeks at most
So it is up to you :)

**Comment by redbaron** [comment]
Will new grape change it's API?

**Comment by bioothod** [comment]
It will be almost completely new project with quite different inner logic, but starting point API will be actually the same - event string + data. Topology processing will be different - no more shared object, native binary instead.

**Comment by redbaron** [comment]
Could you do a blogpost about what is coming in Grape, why did you start overhaul and what benefits it brings to users, please?

**Comment by bioothod** [comment]
Good point, I will formulate it and publish soon

**Comment by redbaron** [comment]
sorry for  being impatient,  can't help but ask whether new Grape expected to arrive this week? :)

**Comment by bioothod** [comment]
Not yet, but it is very close

**Comment by redbaron** [comment]
sweet! looking forward to it

**Comment by redbaron** [comment]
Can we reopen ticket until it is fixed? Grape can't be built with current cocaine, which discontinued language-plugins support in favour of language specific frameworks.

**Comment by bioothod** [comment]
New grape is out (yet in separate branch)
